// Central per-game presentation metadata (icon for cards, image for schema).
// Keyed by game slug (fileSlug). Used by the gamePreview shortcode and the
// Trinkspiele-hub ItemList schema.
module.exports = {
  "17-und-4":             { icon: "🃏", image: "/assets/17-und-4-kartenwerte.svg" },
  "beer-pong":            { icon: "🍺", image: "/assets/beer-pong-aufstellungen.svg" },
  "bierball":            { icon: "⚾", image: "/assets/bierball-aufbau.svg" },
  "buffalo":             { icon: "✋", image: "" },
  "busfahrer":           { icon: "🚌", image: "/assets/busfahren-ablauf.svg" },
  "cheers-to-the-governor": { icon: "🗣️", image: "/assets/cheers-prinzip.svg" },
  "edward-fortyhands":   { icon: "🍾", image: "/assets/edward-fortyhands-prinzip.svg" },
  "flip-cup":            { icon: "🥤", image: "/assets/flip-cup-technik.svg" },
  "flunkyball":          { icon: "🎯", image: "/assets/flunkyball-feld.svg" },
  "ich-hab-noch-nie":    { icon: "🙊", image: "/assets/ich-hab-noch-nie-ablauf.svg" },
  "jenga-trinkspiel":    { icon: "🧱", image: "/assets/jenga-trinkspiel-ablauf.svg" },
  "arschloch":           { icon: "🃏", image: "/assets/arschloch-rangfolge.svg" },
  "bierjunge":           { icon: "🍺", image: "/assets/bierjunge-prinzip.svg" },
  "kings-cup":           { icon: "👑", image: "/assets/kings-cup-ablauf.svg" },
  "maexchen":            { icon: "🎲", image: "/assets/maexchen-wuerfel.svg" },
  "nageln":              { icon: "🔨", image: "/assets/nageln-aufbau.svg" },
  "picolo":              { icon: "📱", image: "/assets/picolo-prinzip.svg" },
  "power-hour":          { icon: "⏱️", image: "/assets/power-hour-prinzip.svg" },
  "rage-cage":           { icon: "🌀", image: "/assets/rage-cage-ablauf.svg" },
  "schiffe-versenken-trinkspiel": { icon: "🚢", image: "/assets/schiffe-versenken-aufbau.svg" },
  "schocken":            { icon: "🍻", image: "/assets/schocken-wuerfel.svg" },
  "schwimmen":           { icon: "🏊", image: "/assets/schwimmen-kartenwerte.svg" },
  "trink-roulette":      { icon: "🎡", image: "/assets/trink-roulette-aufbau.svg" },
  "uno-trinkspiel":      { icon: "🎴", image: "/assets/uno-trinkspiel-kartenregeln.svg" },
  "wahrheit-oder-pflicht": { icon: "🤫", image: "/assets/wahrheit-oder-pflicht-ablauf.svg" },
  "wasserfall":          { icon: "🌊", image: "/assets/wasserfall-prinzip.svg" },
  "was-wuerdest-du-eher": { icon: "🤔", image: "/assets/was-wuerdest-du-eher-ablauf.svg" },
  "wer-wuerde-eher":     { icon: "👉", image: "/assets/wer-wuerde-eher-ablauf.svg" },
  "wuerfelpoker":        { icon: "🎲", image: "/assets/wuerfelpoker-rangfolge.svg" },
  "beer-die":            { icon: "🎲", image: "/assets/beer-die-aufbau.svg" },
  "snappa":              { icon: "🎲", image: "/assets/snappa-aufbau.svg" },
  "looping-louie":       { icon: "🛩️", image: "/assets/looping-louie-aufbau.svg" },
  "medusa":              { icon: "🐍", image: "/assets/medusa-ablauf.svg" },
  "werwolf-trinkspiel":  { icon: "🐺", image: "/assets/werwolf-trinkspiel-ablauf.svg" },
  "stadt-land-fluss":    { icon: "✏️", image: "/assets/og/stadt-land-fluss.jpg" },
  "wer-bin-ich":         { icon: "🧠", image: "/assets/og/wer-bin-ich.jpg" },
  "pferderennen":        { icon: "🐎", image: "/assets/og/pferderennen.jpg" },
  "pyramide":            { icon: "🔺", image: "/assets/og/pyramide.jpg" },
  "hoch-oder-tief":      { icon: "🎴", image: "/assets/og/hoch-oder-tief.jpg" },
  "tabu-trinkspiel":     { icon: "🗣️", image: "/assets/og/tabu-trinkspiel.jpg" },
};
